# Use Ubuntu as the base image
FROM mcr.microsoft.com/devcontainers/base:ubuntu

# Install necessary dependencies
RUN apt-get update && \
    apt-get install -y curl git unzip xz-utils zip libglu1-mesa

# Flutter
RUN git clone -b master https://github.com/flutter/flutter.git /sdk/flutter
RUN ./sdk/flutter/bin/flutter --version
ENV PATH="/sdk/flutter/bin:${PATH}"
RUN chmod -R 777 /sdk/flutter/bin


