FROM mcr.microsoft.com/devcontainers/base:ubuntu

# Apt
RUN apt-get update && \
    apt-get install -y wget xz-utils git curl file unzip zip openjdk-17-jdk && \
    rm -rf /var/lib/apt/lists/*

# Flutter
RUN git clone -b master https://github.com/flutter/flutter.git /sdk/flutter
ENV PATH="/sdk/flutter/bin:${PATH}"

# Install Android SDK
RUN yes | /sdk/flutter/bin/flutter doctor --android-licenses

# Download and install Chrome
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
    apt-get update && \
    apt-get install -y ./google-chrome-stable_current_amd64.deb && \
    rm google-chrome-stable_current_amd64.deb

    
# Install Linux toolchain
RUN apt-get update && apt-get install -y clang cmake ninja-build pkg-config

# Set environment variables
ENV ANDROID_HOME=/opt/android-sdk
ENV PATH="${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools:${PATH}"

# Set environment variable for Chrome executable
ENV CHROME_EXECUTABLE=/usr/bin/google-chrome-stable