name: Flutter Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.21.0-0.0.pre'
          channel: 'Beta' 
      - run: flutter --version
      
      - name: install app dependencies
        working-directory: ./app
        run: flutter pub get

      - name: Run tests
        working-directory: ./app
        run: flutter test

      - name: Build flutter web
        working-directory: ./app
        run: flutter build web