name: Github Pages Deployment

on:
   workflow_call:
  
  jobs:
    call-workflow:
    uses: sydneyg2021/Flutter-Web/.github/workflows/build.yml@v1

    deployment:
      steps:
        - name: Web Deploy
          working-directory: ./.github/workflow
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./app/build/web/