name: Github Pages Deployment

on:
    workflow_call:  
  
  jobs:
    deployment:
      steps:
        - name: Web Deploy
          working-directory: ./.github/workflow
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./app/build/web/