name: Deploy to GitHub Pages

on:
  workslow_call:
    branches:
      - main

 permissions:
      contents: write
      pages: write     
      id-token: write  

jobs:
  deployment:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Web App Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./app/build/web/
      
      - name: configure github pages
        uses: actions/configure-pages@v3
        with:
          static_site_generator: next

      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v1